apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-gateway-hpa
  namespace: swasthya-setu
spec:
  minReplicas: 2
  maxReplicas: 6
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: auth-service-hpa
  namespace: swasthya-setu
spec:
  minReplicas: 2
  maxReplicas: 6
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: appointment-service-hpa
  namespace: swasthya-setu
spec:
  minReplicas: 2
  maxReplicas: 6
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: patient-service-hpa
  namespace: swasthya-setu
spec:
  minReplicas: 2
  maxReplicas: 6
