apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: swasthya-setu

resources:
  - ../k8s
  - network-policies.yaml
  - pdb.yaml

patches:
  - path: hpa-production.yaml
  - path: ingress-tls.yaml
