spring.application.name=hospital-service
server.port=${SERVER_PORT:8084}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/swasthyasetudb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:myuser}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:myuser}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
