apiVersion: v1
kind: Secret
metadata:
  name: swasthya-secrets
type: Opaque
stringData:
  postgres-user: myuser
  postgres-password: myuser
  rabbitmq-user: guest
  rabbitmq-password: guest
  jwt-secret: change-me-to-at-least-32-characters
  spring-mail-username: ""
  spring-mail-password: ""
