apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: swasthya
data:
  init-dbs.sql: |
    CREATE DATABASE auth_db;
    CREATE DATABASE patient_db;
    CREATE DATABASE provider_db;
    CREATE DATABASE appointment_db;
    CREATE DATABASE qr_db;
