apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-service
spec:
  template:
    spec:
      containers:
        - name: appointment-service
          env:
            - name: INTERNAL_SERVICE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: swasthya-secrets
                  key: internal-service-token
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-service
spec:
  template:
    spec:
      containers:
        - name: patient-service
          env:
            - name: INTERNAL_SERVICE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: swasthya-secrets
                  key: internal-service-token
