apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: swasthya-setu

resources:
  - namespace.yaml
  - app-config.yaml
  - app-secrets.yaml
  - postgres.yaml
  - redis.yaml
  - rabbitmq.yaml
  - mailpit.yaml
  - app-services.yaml
  - frontends.yaml
  - ingress.yaml
  - hpa.yaml
  - elk.yaml
  - monitoring.yaml
